services:
  api:
      build:
        context: .
        args:
          SIGNALAPI_PORT: "8082"
          HALO_URL: "http://localhost:8081"
      ports:
        - "8082:8082"
      environment:
        SIGNALAPI_PORT: "8082"
        HALO_URL: "http://localhost:8081"
        NECTAR_URL: "http://localhost:5175/nectar"
        POLVO_URL: "http://localhost:5173/polvo"

