services:
  api:
    build:
      args:
        SIGNALAPI_PORT: "8082"
        HALO_URL: "http://halo:8080"
        NECTAR_URL: "http://localhost:5175/nectar"
        POLVO_URL: "http://localhost:5173/profile"
    ports:
      - "8082:8082"
    environment:
      SIGNALAPI_PORT: "8082"
      HALO_URL: "http://halo:8080"
      NECTAR_URL: "http://localhost:5175/nectar"
      POLVO_URL: "http://localhost:5173/profile"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - shared


networks:
  shared:
    external: true

